### ISSUE TITLE
Importing custom JARs

### ISSUE THREAD

**Issue by lail0ken** [DouglasDwyer/IntegratedMinecraftServer#3]
Uploading a custom JAR leaving it uploading and no change.
Replicated this on Win10 Pro, on Chrome, Firefox and Edge.

If you add the custom JAR into the directory of the Vanilla JAR it is not detected either.

**Comment by DouglasDwyer** [comment]
This issue was due to the inexistence of the folder that custom JARs were supposed to upload to.  It has been fixed in commit 473fc4e621c0c2de9e073a3e4756597e15cb377a and should roll out as part of the v1.0.1.2 release.  Thank you for letting me know!
