### ISSUE TITLE
Question on Minecraft variants supported 

### ISSUE THREAD

**Issue by djqifs** [DouglasDwyer/IntegratedMinecraftServer#6]
The Java (and variants) seem to operate pretty much as expected, but can I clarify if IMS is intended to support to Bedrock Dedicated Server or just the "client, UWP version" of Bedrock server or both? (I'm suspecting its just the UWP variant, which has some differences to BDS)

I ask as I run several different server variants for Minecraft and I'm just looking at options to ease the overall management of them. As I say above, the Java is all fine. However, I started looking into BDS today, and although I've inferred some avenues from older versions in which "Bedrock" software was included in the installation (referencing BedrockTemplate location and the UWP version of Bedrock), there doesn't seem to be much about whether IMS will (or is intended to) function for BDS or how one might configure it. Just figured I'd ask

I can _potentially_ look at migrating the BDS instances to UWP, although there are some differences with things like how addons are set up. A lot of families seem to be setting up BDS instances with all the COVID lockdown happening around the world.

Cheers for the good work!

**Comment by DouglasDwyer** [comment]
Hello. Thank you for your interest in this project. Can you elaborate on the difference between BDS and the UWP version? I'm not really certain what you mean - as far as I can tell, there is only one version of an official Bedrock server available (for download [here](https://www.minecraft.net/en-us/download/server/bedrock)), and it's just a console application, not built on the Universal Windows Platform. This is the version that IMS downloads if you create a Bedrock server, and was contained in BedrockTemplate before I removed it (for copyright reasons). If there is a different version of Bedrock server which Mojang officially supports, I'd be happy to add support for it in the future :)
