### ISSUE TITLE
Custom Install Path fails to start service

### ISSUE THREAD

**Issue by bbeenn1** [DouglasDwyer/IntegratedMinecraftServer#7]
Service is installed with default path when choosing a custom directory to install to.

**Comment by DouglasDwyer** [comment]
Hello - thank you for opening an issue regarding this bug. I've actually known about this issue for some time, but real life obligations prevented me from updating IMS. That being said, I have some free time now, so I will look into releasing a patch in the next few days. I might not even need to release a new version of IMS; just rebuild the installer, which uses a `.bat` file for setting up the Windows service.

**Comment by DouglasDwyer** [comment]
Fixed alongside the release of version 1.0.1.4.
