### ISSUE TITLE
Couldn't obtain data about the latest version of Bedrock Dedicated Server! Attempting to start using last version...

### ISSUE THREAD

**Issue by AlexFielder** [DouglasDwyer/IntegratedMinecraftServer#8]
Hi there,

I hope this finds you well; I have just installed this tool on Windows Server 2019 and, after some teething troubles with registering the service correctly, managed to start IMS.

I notice there is an .xml file containing download links for the various Java version(s)- but not for Bedrock. Can I add the latest download link to this file or do I need to download the relevant zip file manually?

Thanks,

Alex.

**Comment by DouglasDwyer** [comment]
Hello Alex,

Thanks for reaching out. The Bedrock server, unfortunately, is not "versioned" like the Java server. Mojang doesn't provide a history of Bedrock servers; to my knowledge, they only ever offer the latest download to match the version available on the Windows Store and other platforms. Bedrock updates do happen automatically, but are controlled by the file `IMS-Distribution/bedrock-version.xml` in this repository. As I've been busy at college, I haven't had time to make any recent updates to the IMS project. I suspect therefore that the Bedrock version file is out of date. I will go ahead and update it to the latest version, and your IMS distribution should see it automatically.

If registering the service was problematic for you, would you mind posting another GitHub issue? I thought I fixed that problem in version 1.0.1.4.

Thanks for deciding to try out IMS. I hope it is useful for you.

**Comment by DouglasDwyer** [comment]
I have gone ahead and added the new version to the Bedrock distribution file, and will now close this issue. Feel free to reopen it if the issue persists. Please let me know if there is anything that I can do!

**Comment by AlexFielder** [comment]
Thanks Douglas, much appreciated. :-)
